// Code generated by sqlc. DO NOT EDIT.
// Run `make sqlc` to regenerate after changing sql/queries/*.sql
package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type OrderItem struct {
	OrderID   uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
	UnitPrice int64
}

type OutboxMessage struct {
	ID        uuid.UUID
	Topic     string
	Payload   json.RawMessage
	CreatedAt time.Time
}

// --- param structs ---

type InsertOrderParams struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	Status     string
}

type InsertOrderItemParams struct {
	OrderID   uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
	UnitPrice int64
}

type InsertOutboxMessageParams struct {
	ID      uuid.UUID
	Topic   string
	Payload json.RawMessage
}

// GetOrderRow is returned by the GetOrder query which aggregates items via json_agg.
type GetOrderRow struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	Status     string
	CreatedAt  time.Time
	Items      json.RawMessage // []{"product_id","quantity","unit_price"}
}

type UnpublishedOutboxRow struct {
	ID      uuid.UUID
	Topic   string
	Payload json.RawMessage
}
