// Code generated by sqlc. DO NOT EDIT.
package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// DBTX is satisfied by both *pgxpool.Pool and pgx.Tx, enabling WithTx.
type DBTX interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
	QueryRow(context.Context, string, ...any) pgx.Row
}

type Queries struct{ db DBTX }

func New(db DBTX) *Queries              { return &Queries{db: db} }
func (q *Queries) WithTx(tx pgx.Tx) *Queries { return &Queries{db: tx} }

const insertOrder = `
INSERT INTO orders (id, customer_id, status)
VALUES ($1, $2, $3)`

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.Exec(ctx, insertOrder, arg.ID, arg.CustomerID, arg.Status)
	return err
}

const insertOrderItem = `
INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES ($1, $2, $3, $4)`

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderItem,
		arg.OrderID, arg.ProductID, arg.Quantity, arg.UnitPrice)
	return err
}

const insertOutboxMessage = `
INSERT INTO outbox_messages (id, topic, payload)
VALUES ($1, $2, $3)`

func (q *Queries) InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error {
	_, err := q.db.Exec(ctx, insertOutboxMessage, arg.ID, arg.Topic, arg.Payload)
	return err
}

const getOrder = `
SELECT
    o.id, o.customer_id, o.status, o.created_at,
    COALESCE(
        json_agg(json_build_object(
            'product_id', oi.product_id,
            'quantity',   oi.quantity,
            'unit_price', oi.unit_price
        )) FILTER (WHERE oi.order_id IS NOT NULL),
        '[]'
    ) AS items
FROM orders o
LEFT JOIN order_items oi ON oi.order_id = o.id
WHERE o.id = $1
GROUP BY o.id`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var r GetOrderRow
	return r, row.Scan(&r.ID, &r.CustomerID, &r.Status, &r.CreatedAt, &r.Items)
}

const unpublishedOutbox = `
SELECT id, topic, payload
FROM outbox_messages
WHERE published_at IS NULL
ORDER BY created_at
LIMIT $1`

func (q *Queries) UnpublishedOutboxMessages(ctx context.Context, limit int32) ([]UnpublishedOutboxRow, error) {
	rows, err := q.db.Query(ctx, unpublishedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var result []UnpublishedOutboxRow
	for rows.Next() {
		var r UnpublishedOutboxRow
		if err := rows.Scan(&r.ID, &r.Topic, &r.Payload); err != nil {
			return nil, err
		}
		result = append(result, r)
	}
	return result, rows.Err()
}

const markOutboxPublished = `
UPDATE outbox_messages SET published_at = now()
WHERE id = ANY($1::uuid[])`

func (q *Queries) MarkOutboxPublished(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, ids)
	return err
}
