// Code generated by sqlc. DO NOT EDIT.
package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	InsertOrder(ctx context.Context, arg InsertOrderParams) error
	InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error
	InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error
	GetOrder(ctx context.Context, id uuid.UUID) (GetOrderRow, error)
	UnpublishedOutboxMessages(ctx context.Context, limit int32) ([]UnpublishedOutboxRow, error)
	MarkOutboxPublished(ctx context.Context, ids []uuid.UUID) error
}
